plugins {
    id 'java'
    id 'maven-publish'
    id("xyz.jpenilla.run-paper") version "3.0.2"
    id("com.gradleup.shadow") version "9.2.2"
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21" apply false
}

/*
|--------------------------------------------------------------------------
| Feature Flags
|--------------------------------------------------------------------------
*/

def usePaperweight = providers.gradleProperty("usePaperweight")
        .map { it.toBoolean() }
        .getOrElse(false)

def enableUtils = providers.gradleProperty("enable_utils")
        .map { it.toBoolean() }
        .getOrElse(false)

def enableDate = providers.gradleProperty("enable_date")
        .map { it.toBoolean() }
        .getOrElse(false)

def enableConfig = providers.gradleProperty("enable_config")
        .map { it.toBoolean() }
        .getOrElse(false)

def enableScheduler = providers.gradleProperty("enable_scheduler")
        .map { it.toBoolean() }
        .getOrElse(false)

def enableCommand = providers.gradleProperty("enable_command")
        .map { it.toBoolean() }
        .getOrElse(false)

def enableGui = providers.gradleProperty("enable_gui")
        .map { it.toBoolean() }
        .getOrElse(false)

def enableDatabase = providers.gradleProperty("enable_database")
        .map { it.toBoolean() }
        .getOrElse(false)

if (usePaperweight) {
    apply plugin: "io.papermc.paperweight.userdev"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(java_version)
    }
}

group = group_name
version = plugin_version

repositories {
    mavenCentral()
    maven {
        name = "papermc-repo"
        url = "https://repo.papermc.io/repository/maven-public/"
    }
    maven {
        name = "codemc-repo"
        url = "https://repo.codemc.io/repository/maven-public/"
    }
    maven {
        name = "jitpack.io"
        url = "https://jitpack.io"
    }
    maven {
        name = "ender-zone-repo"
        url = "https://ci.ender.zone/plugin/repository/everything/"
    }

    maven {
        name = "nexo-items-repo"
        url = "https://repo.nexomc.com/releases"
    }

    maven {
        name = "hmc-wraps-repo"
        url = "https://repo.hibiscusmc.com/releases/"
    }

    maven {
        name = "geyser-repo"
        url = uri("https://repo.opencollab.dev/main/")
    }
}

dependencies {
    compileOnly "io.papermc.paper:paper-api:${minecraft_version}.build.+"
    if (usePaperweight) {
        paperweight.paperDevBundle("${minecraft_version}.build.+")
    }

    if (enableUtils) {
        implementation "com.github.WonkyLibs:Util:${utils_version}"
    }

    if (enableDate) {
        implementation "com.github.WonkyLibs:Date:${date_version}"
    }
    if (enableConfig) {
        implementation "com.github.WonkyLibs:Config:${config_version}"
    }

    if (enableCommand) {
        implementation "com.github.WonkyLibs:Command:${command_version}"
    }

    if (enableGui) {
        implementation "com.github.WonkyLibs:GUI:${gui_version}"
    }

    if (enableDatabase) {
        implementation "com.github.Wonkglorg:DatabaseUtils:${databaseutils_version}"
    }
    compileOnly "org.jetbrains:annotations:${jetbrains_annotation_version}"
    compileOnly "org.projectlombok:lombok:${lombok_version}"
    annotationProcessor "org.projectlombok:lombok:${lombok_version}"

    //Core dependencies
    compileOnly 'net.milkbowl.vault:VaultAPI:1.7'

    //FoliaLib
    implementation 'com.github.technicallycoded:FoliaLib:0.4.4'

    //Plugin Dependencies
    compileOnly "org.geysermc.floodgate:api:${floodgate_version}"
    compileOnly "org.geysermc.geyser:api:${geyser_version}"

    //Custom item Dependencies
    compileOnly "com.nexomc:nexo:${nexo_version}"
    compileOnly "de.skyslycer.hmcwraps:api:${hmcwraps_version}"

    //test dependencies
    testImplementation platform("org.junit:junit-bom:${junit_version}")
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

    testImplementation 'net.milkbowl.vault:VaultAPI:1.7'
    testImplementation "org.mockito:mockito-core:${mockito_version}"
    testImplementation "io.papermc.paper:paper-api:${minecraft_version}.build.+"
    testImplementation "org.mockbukkit.mockbukkit:mockbukkit-v26.1.2:4.114.0"


}

tasks {
    runServer {
        minecraftVersion(minecraft_version)
    }
}

test {
    useJUnitPlatform()
}

processResources {
    def props = [version         : version,
                 minecraftVersion: minecraft_version,
                 name            : plugin_name,
                 api_version     : plugin_api_version,
                 description     : plugin_description,
                 author          : author

    ]
    inputs.properties props
    filesMatching('plugin.yml') {
        expand props
    }
}

tasks.named("jar") {
    enabled = false
}

def jarOutputDir = providers.gradleProperty("jar_output_dir")
        .getOrElse("$buildDir/libs")

tasks.named("shadowJar") {
    archiveClassifier.set("")

    destinationDirectory.set(file(jarOutputDir))

    relocate("com.tcoded.folialib", "com.wonkglorg.shop.lib.folialib")


    relocate("com.wonkglorg.minecraft.config", "com.wonkglorg.shop.lib.config")

    doLast {
        println("Shadow jar generated at: ${archiveFile.get().asFile.absolutePath}")
    }
}

tasks.named("build") {
    dependsOn("shadowJar")
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact tasks.shadowJar
        }
    }
}

