group_name=com.wonkglorg
author = [Wonkglorg]
minecraft_version=26.2
java_version=25
plugin_name=Shop
plugin_version=2.0.0
plugin_description = Easily create shops to buy or sell items!
plugin_api_version = 26.2

#build params
jar_output_dir=build/out

#feature flags
usePaperweight=true
enable_utils=true
enable_date=true
enable_config=true
enable_scheduler=false
enable_command=true
enable_gui=false
enable_database=true

#Dependencies
utils_version= 1.1.0
date_version= 1.0.0
config_version= 7.2.1
gui_version= 948aea2d94
command_version= 2.0.2
scheduler_version= 2.0.0
databaseutils_version= 0f2308e073

#Plugin Dependencies
floodgate_version = 2.2.4-SNAPSHOT

#test dependencies
jetbrains_annotation_version = 26.0.2
lombok_version = 1.18.42
junit_version = 5.11.3
mockito_version = 5.20.0