group_name=com.wonkglorg
author = Wonkglorg
minecraft_version=26.1.2
java_version=25
plugin_name=PluginTemplate21_1_2
plugin_version=1.0.0
plugin_description = Insert Description
plugin_api_version = 26.1.2

#build params
jar_output_dir=build/out

#feature flags
usePaperweight=false
enable_config=true
enable_scheduler=true
enable_command=false
enable_gui=false
enable_database=false

#Dependencies
utilitylib_config_version= 3.1.0
utilitylib_gui_version= 1.3.0
utilitylib_command_version= 1.2.2
utilitylib_scheduler_version= 1.1.0
databaseutils_version= 3.0.0

#test dependencies
jetbrains_annotation_version = 26.0.2
lombok_version = 1.18.42
junit_version = 5.11.3
mockito_version = 5.20.0