# These sounds are guaranteed to work only on 1.15.x-1.21.x servers.
# If you update in the future, look for actual names at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
# You can also check if there is already an update to PrivateMessages plugin in web.
# Then re-generate new default file by deleting this one - plugin will auto-detect server version and place valid config.
# DisplayName & Description paramaters aren't required - you can leave them blank or delete their entries completely if you don't want to modify them.
# Formatting (legacy or MiniMessage, depending on your choice in config.yml) is supported.
1:
  Sound: ENTITY_EGG_THROW,1,0.5
  DisplayName: "Egg throw"
  Description:
    - "Sound played when egg gets thrown"
    - "(modified)."
2:
  # Each sound consists of sound name, volume and pitch separated by commas.
  # 2nd parameter is volume, 3rd parameter - pitch.
  # 4th parameter is delay (in ticks) before playing next sound in order - it is not required if there are no more sounds to play.
  # Each sound entry is separated by ';' sign.
  # In following example we have two noteblock plings playing with volume and pitch of 1 and delay of 3 ticks after first pling.
  # It's also possible to put sound name only without volume and pitch if only one sound entry is present - then volume and pitch use default value (1).
  Sound: BLOCK_NOTE_BLOCK_PLING,1,1,3;BLOCK_NOTE_BLOCK_PLING,1,1
  DisplayName: "2x Noteblock pling"
  Description:
    - "Noteblock pling played twice with"
    - "a 3 ticks delay after first one."
3:
  Sound: BLOCK_BEACON_DEACTIVATE,1,1,2;BLOCK_BEACON_DEACTIVATE,1,1
  DisplayName: "2x Beacon deactivate"
  Description:
    - "Beacon deactivation played twice with"
    - "a 2 ticks delay after first one."
4:
  Sound: ENTITY_ENDERMAN_TELEPORT,1,1,2;ENTITY_ENDERMAN_TELEPORT,1,1
  DisplayName: "2x Enderman teleport"
  Description:
    - "Enderman teleport played twice with"
    - "a 2 ticks delay after first one."
5:
  Sound: ENTITY_FIREWORK_ROCKET_LAUNCH,1,1,1;ENTITY_FIREWORK_ROCKET_LAUNCH,1,1,1;ENTITY_FIREWORK_ROCKET_LAUNCH,1,1
  DisplayName: "3x Firework launch"
  Description:
    - "Firework launch played 3 times with"
    - "a 1 tick delay between each one."
6:
  Sound: ENTITY_PLAYER_LEVELUP,1,0.6
  DisplayName: "Player LevelUp"
  Description:
    - "Player level up sound (modified)."
7:
  Sound: ENTITY_PLAYER_LEVELUP
  DisplayName: "Player LevelUp [2]"
  Description:
    - "Player level up sound."
8:
  Sound: ENTITY_PLAYER_LEVELUP,1,1.2
  DisplayName: "Player LevelUp [3]"
  Description:
    - "Player level up sound (modified)."
9:
  Sound: ENTITY_PLAYER_LEVELUP,1,1.5
  DisplayName: "Player LevelUp [4]"
  Description:
    - "Player level up sound (modified)"
10:
  Sound: ENTITY_PLAYER_LEVELUP,1,1.8
  DisplayName: "Player LevelUp [5]"
  Description:
    - "Player level up sound (modified)."
11:
  Sound: ENTITY_BAT_HURT
  DisplayName: "Bat hurt"
  Description:
    - "Sound played when bat gets hurt."
12:
  Sound: ENTITY_BAT_HURT,1,0.5
  DisplayName: "Bat hurt [2]"
  Description:
    - "Sound played when bat gets hurt (modified)."
13:
  Sound: ENTITY_SHEEP_HURT,1,1.5
  DisplayName: "Sheep hurt"
  Description:
    - "Sound played when sheep gets hurt (modified)."
14:
  Sound: ENTITY_PIG_DEATH,1,1.5
  DisplayName: "Pig death"
  Description:
    - "Sound played when pig dies (modified)."
15:
  Sound: ENTITY_ENDERMAN_TELEPORT,1,0.7
  DisplayName: "Enderman teleport"
  Description:
    - "Sound played when enderman teleports"
    - "(modified)."
16:
  Sound: ENTITY_PARROT_AMBIENT,1,0.5
  DisplayName: "Parrot ambient"
  Description:
    - "Parrot ambient noise (modified)."
17:
  Sound: ENTITY_GENERIC_EXPLODE
  DisplayName: "Generic explosion"
  Description:
    - "Generic explosion sound."
18:
  Sound: ENTITY_BLAZE_AMBIENT
  DisplayName: "Blaze ambient"
  Description:
    - "Blaze ambient noise."
19:
  Sound: ENTITY_CHICKEN_HURT
  DisplayName: "Chicken hurt"
  Description:
    - "Sound played when chicken gets hurt."
20:
  Sound: ENTITY_GHAST_SCREAM
  DisplayName: "Ghast scream"
  Description:
    - "Sound played when ghast screams."
21:
  Sound: ENTITY_WITHER_SHOOT,1,0.8
  DisplayName: "Wither shoot"
  Description:
    - "Sound played when wither launches"
    - "his missiles (modified)."
22:
  Sound: BLOCK_NOTE_BLOCK_PLING
  DisplayName: "Noteblock pling"
  Description:
    - "Sound played on interaction with noteblock."
23:
  Sound: BLOCK_ANVIL_USE,1,2
  DisplayName: "Anvil use"
  Description:
    - "Sound played on interaction with anvil."
24:
  Sound: BLOCK_ANVIL_LAND,1,1.5
  DisplayName: "Anvil land"
  Description:
    - "Sound played on anvil landing."
25:
  Sound: ENTITY_ZOMBIE_ATTACK_IRON_DOOR
  DisplayName: "Zombie attack iron door"
  Description:
    - "Sound played when zombie attacks iron door."
26:
  Sound: ENTITY_ZOMBIE_DEATH
  DisplayName: "Zombie death"
  Description:
    - "Sound played when zombie dies."
27:
  Sound: ENTITY_SPIDER_AMBIENT,1,1.3
  DisplayName: "Spider ambient"
  Description:
    - "Spider ambient noise (modified)."
28:
  Sound: ENTITY_ENDERMAN_HURT,1,1.25
  DisplayName: "Enderman hurt"
  Description:
    - "Sound played when enderman gets hurt"
    - "(modified)."
29:
  Sound: ENTITY_PLAYER_DEATH
  DisplayName: "Player death"
  Description:
    - "Sound played when player dies."
30:
  Sound: ENTITY_PLAYER_HURT_ON_FIRE,1,1.15
  DisplayName: "Player hurt on fire"
  Description:
    - "Sound played when player gets"
    - "hurt by fire (modified)."
31:
  Sound: ENTITY_ITEM_PICKUP,1,1.15
  DisplayName: "Item pickup"
  Description:
    - "Sound played when item gets"
    - "picked up (modified)."
32:
  Sound: ENTITY_ITEM_BREAK,1,0.7
  DisplayName: "Item break"
  Description:
    - "Sound played when item gets"
    - "destroyed (modified)."
33:
  Sound: ENTITY_FIREWORK_ROCKET_LAUNCH
  DisplayName: "Firework launch"
  Description:
    - "Sound played when firework"
    - "rocket is launched"
34:
  Sound: ENTITY_ENDER_DRAGON_SHOOT
  DisplayName: "Enderdragon shoot"
  Description:
    - "Sound played when enderdragon"
    - "launches his missiles."
35:
  Sound: ENTITY_ENDER_DRAGON_HURT
  DisplayName: "Enderdragon shoot"
  Description:
    - "Sound played when enderdragon"
    - "gets hurt."
36:
  Sound: UI_BUTTON_CLICK,1,0.8
  DisplayName: "UI button click"
  Description:
    - "Sound played when UI button"
    - "gets clicked (modified)."
37:
  Sound: ITEM_TRIDENT_THROW
  DisplayName: "Trident throw"
  Description:
    - "Sound played when trident gets thrown."
38:
  Sound: ITEM_CROSSBOW_SHOOT
  DisplayName: "Crossbow shoot"
  Description:
    - "Sound played on crossbow shoot."
39:
  Sound: BLOCK_BEACON_DEACTIVATE,1,2
  DisplayName: "Beacon deactivate"
  Description:
    - "Sound played on beacon deactivation"
    - "(modified)."
40:
  Sound: ENTITY_PANDA_BITE,1,1.2
  DisplayName: "Panda bite"
  Description:
    - "Sound played on panda bite"
    - "(modified)."
41:
  Sound: ENTITY_WITCH_DEATH,1,1.3
  DisplayName: "Witch death"
  Description:
    - "Sound played when witch dies"
    - "(modified)."
42:
  Sound: ENTITY_DOLPHIN_PLAY
  DisplayName: "Dolphin play"
  Description:
    - "Sound played when dolphin plays."
43:
  Sound: ENTITY_BEE_DEATH,1,2
  DisplayName: "Bee death"
  Description:
    - "Sound played when bee dies"
    - "(modified)."
44:
  Sound: ENTITY_BEE_STING,1,0.5
  DisplayName: "Bee sting"
  Description:
    - "Sound played when bee stings"
    - "(modified)."
45:
  Sound: BLOCK_GLASS_BREAK,1,0.5
  DisplayName: "Glass break"
  Description:
    - "Sound played when glass breaks"
    - "(modified)."
46:
  Sound: ENTITY_GENERIC_HURT,1,0.5
  DisplayName: "Entity hurt"
  Description:
    - "Sound played when entity gets hurt."
